import fs from "node:fs/promises";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";

const outputDir = "../outputs/generalization_test";
await fs.mkdir(outputDir, { recursive: true });

const codes = {
  "交通事故": "ACCIDENT",
  "道路拥堵": "CONGESTION",
  "道路施工": "CONSTRUCTION",
  "交通管制": "TRAFFIC_CONTROL",
  "设施故障": "FACILITY_FAILURE",
  "恶劣天气影响": "WEATHER_IMPACT",
  "违法行为": "VIOLATION",
};

const fields = [
  "source_text",
  "event_type",
  "event_type_code",
  "event_subtype",
  "event_time_text",
  "location",
  "road_name",
  "vehicles_involved",
  "vehicle_count",
  "casualties",
  "injured_count",
  "death_count",
  "road_impact",
  "occupied_lane",
  "congestion_level",
  "disposal_measure",
  "event_status",
];

function standard(record) {
  const base = {
    source_text: record.source_text,
    event_type: record.event_type,
    event_type_code: codes[record.event_type],
    event_subtype: record.event_subtype,
    event_time_text: record.event_time_text ?? null,
    location: record.location ?? null,
    road_name: record.road_name ?? null,
    vehicles_involved: record.vehicles_involved ?? [],
    vehicle_count: record.vehicle_count ?? null,
    casualties: record.casualties ?? null,
    injured_count: record.injured_count ?? null,
    death_count: record.death_count ?? null,
    road_impact: record.road_impact ?? null,
    occupied_lane: record.occupied_lane ?? null,
    congestion_level: record.congestion_level ?? "未知",
    disposal_measure: record.disposal_measure ?? null,
    event_status: record.event_status ?? "未知",
  };
  return Object.fromEntries(fields.map((field) => [field, base[field]]));
}

const records = [
  {
    id: "G001",
    source_type: "事故警情",
    difficulty: "简单",
    source_text: "报警人称，银杏路与翠竹街路口两辆轿车追尾，占用一条左转车道，现场通行缓慢。",
    event_type: "交通事故",
    event_subtype: "追尾事故",
    location: "银杏路与翠竹街路口",
    road_name: "银杏路；翠竹街",
    vehicles_involved: ["轿车"],
    vehicle_count: 2,
    road_impact: "占用一条左转车道",
    occupied_lane: "左转车道",
    congestion_level: "缓慢",
    event_status: "发生中",
  },
  {
    id: "G002",
    source_type: "道路巡查",
    difficulty: "简单",
    source_text: "巡查发现，松涛路早高峰车流量大，车辆行驶缓慢，未见事故和施工。",
    event_type: "道路拥堵",
    event_subtype: "通行缓慢",
    event_time_text: "早高峰",
    location: "松涛路",
    road_name: "松涛路",
    road_impact: "车流量大，车辆行驶缓慢",
    congestion_level: "缓慢",
    event_status: "发生中",
  },
  {
    id: "G003",
    source_type: "交通新闻",
    difficulty: "简单",
    source_text: "因雨水管网改造，明珠西路外侧车道正在施工，车辆可从内侧车道通行。",
    event_type: "道路施工",
    event_subtype: "占道施工",
    location: "明珠西路外侧车道",
    road_name: "明珠西路",
    road_impact: "外侧车道施工，车辆从内侧车道通行",
    occupied_lane: "外侧车道",
    congestion_level: "未知",
    event_status: "发生中",
  },
  {
    id: "G004",
    source_type: "道路巡查",
    difficulty: "简单",
    source_text: "巡查至海棠大道南段时，发现临时交通管制，车辆需按现场指示绕行。",
    event_type: "交通管制",
    event_subtype: "临时管制",
    location: "海棠大道南段",
    road_name: "海棠大道",
    road_impact: "车辆需按现场指示绕行",
    congestion_level: "未知",
    disposal_measure: "现场指示绕行",
    event_status: "发生中",
  },
  {
    id: "G005",
    source_type: "群众投诉",
    difficulty: "简单",
    source_text: "市民反映，望月街口信号灯持续黄闪，车辆通过时相互抢行。",
    event_type: "设施故障",
    event_subtype: "信号灯故障",
    location: "望月街口",
    road_name: "望月街",
    road_impact: "车辆通过时相互抢行",
    congestion_level: "未知",
    event_status: "发生中",
  },
  {
    id: "G006",
    source_type: "道路巡查",
    difficulty: "简单",
    source_text: "巡查记录显示，北山快速路K12路段突降大雾，能见度较低，车辆低速通行。",
    event_type: "恶劣天气影响",
    event_subtype: "大雾影响",
    location: "北山快速路K12路段",
    road_name: "北山快速路",
    vehicles_involved: ["车辆"],
    road_impact: "车辆低速通行",
    congestion_level: "缓慢",
    event_status: "发生中",
  },
  {
    id: "G007",
    source_type: "群众投诉",
    difficulty: "简单",
    source_text: "群众投诉，文华街地铁口外多辆私家车违停，占用非机动车道。",
    event_type: "违法行为",
    event_subtype: "违法停车",
    location: "文华街地铁口外",
    road_name: "文华街",
    vehicles_involved: ["私家车", "非机动车"],
    road_impact: "占用非机动车道",
    occupied_lane: "非机动车道",
    congestion_level: "未知",
    event_status: "发生中",
  },
  {
    id: "G008",
    source_type: "事故警情",
    difficulty: "简单",
    source_text: "接警称，紫荆桥东口一辆出租车与电动自行车发生碰撞，骑车人轻微受伤。",
    event_type: "交通事故",
    event_subtype: "机动车与非机动车碰撞",
    location: "紫荆桥东口",
    road_name: "紫荆桥",
    vehicles_involved: ["出租车", "电动自行车"],
    vehicle_count: 2,
    casualties: "骑车人轻微受伤",
    injured_count: 1,
    death_count: 0,
    congestion_level: "未知",
    event_status: "发生中",
  },
  {
    id: "G009",
    source_type: "交通新闻",
    difficulty: "简单",
    source_text: "晚高峰期间，湖滨北路商圈周边车辆排队明显，交警提醒错峰出行。",
    event_type: "道路拥堵",
    event_subtype: "车辆排队",
    event_time_text: "晚高峰期间",
    location: "湖滨北路商圈周边",
    road_name: "湖滨北路",
    road_impact: "车辆排队明显",
    congestion_level: "拥堵",
    disposal_measure: "提醒错峰出行",
    event_status: "发生中",
  },
  {
    id: "G010",
    source_type: "道路巡查",
    difficulty: "简单",
    source_text: "巡查发现，锦绣路人行道旁施工围挡外扩，机动车道变窄。",
    event_type: "道路施工",
    event_subtype: "施工围挡影响通行",
    location: "锦绣路人行道旁",
    road_name: "锦绣路",
    road_impact: "施工围挡外扩，机动车道变窄",
    congestion_level: "未知",
    event_status: "发生中",
  },
  {
    id: "G011",
    source_type: "交通新闻",
    difficulty: "简单",
    source_text: "马拉松测试跑期间，晨曦大道部分路段短时封闭，社会车辆禁止通行。",
    event_type: "交通管制",
    event_subtype: "道路封闭",
    location: "晨曦大道部分路段",
    road_name: "晨曦大道",
    vehicles_involved: ["社会车辆"],
    road_impact: "短时封闭，社会车辆禁止通行",
    congestion_level: "未知",
    disposal_measure: "禁止通行",
    event_status: "发生中",
  },
  {
    id: "G012",
    source_type: "群众投诉",
    difficulty: "简单",
    source_text: "市民来电称，星河路隔离护栏倾斜，夜间影响车辆变道观察。",
    event_type: "设施故障",
    event_subtype: "护栏损坏",
    location: "星河路",
    road_name: "星河路",
    road_impact: "夜间影响车辆变道观察",
    congestion_level: "未知",
    event_status: "发生中",
  },
  {
    id: "G013",
    source_type: "道路巡查",
    difficulty: "简单",
    source_text: "受短时暴雨影响，清泉路下穿通道出现积水，小客车通行受阻。",
    event_type: "恶劣天气影响",
    event_subtype: "暴雨积水",
    location: "清泉路下穿通道",
    road_name: "清泉路",
    vehicles_involved: ["小客车"],
    road_impact: "小客车通行受阻",
    congestion_level: "拥堵",
    event_status: "发生中",
  },
  {
    id: "G014",
    source_type: "事故警情",
    difficulty: "简单",
    source_text: "报警称，云杉路口一辆小货车闯红灯，与正常通行轿车发生刮碰。",
    event_type: "违法行为",
    event_subtype: "闯红灯",
    location: "云杉路口",
    road_name: "云杉路",
    vehicles_involved: ["小货车", "轿车"],
    vehicle_count: 2,
    road_impact: "车辆发生刮碰",
    congestion_level: "未知",
    event_status: "发生中",
  },
  {
    id: "G015",
    source_type: "事故警情",
    difficulty: "简单",
    source_text: "接警信息显示，丹桂路西段一辆面包车侧翻，占用右侧车道，无人员被困。",
    event_type: "交通事故",
    event_subtype: "侧翻事故",
    location: "丹桂路西段",
    road_name: "丹桂路",
    vehicles_involved: ["面包车"],
    vehicle_count: 1,
    casualties: "无人员被困",
    injured_count: 0,
    death_count: 0,
    road_impact: "占用右侧车道",
    occupied_lane: "右侧车道",
    congestion_level: "缓慢",
    event_status: "发生中",
  },
  {
    id: "G016",
    source_type: "道路巡查",
    difficulty: "中等",
    source_text: "巡查至双岭隧道北口时，发现早高峰进城方向车流集中，隧道内车辆走走停停，队尾延伸至匝道口。",
    event_type: "道路拥堵",
    event_subtype: "严重拥堵",
    event_time_text: "早高峰",
    location: "双岭隧道北口进城方向；匝道口",
    road_name: "双岭隧道",
    vehicles_involved: ["车辆"],
    road_impact: "隧道内车辆走走停停，队尾延伸至匝道口",
    congestion_level: "严重拥堵",
    event_status: "发生中",
  },
  {
    id: "G017",
    source_type: "交通新闻",
    difficulty: "中等",
    source_text: "因燃气管线抢修，枫林一路由东向西方向封闭一条直行车道，公交车站临时向前迁移约80米。",
    event_type: "道路施工",
    event_subtype: "道路抢修",
    location: "枫林一路由东向西方向；公交车站",
    road_name: "枫林一路",
    vehicles_involved: ["公交车"],
    road_impact: "封闭一条直行车道，公交车站临时迁移",
    occupied_lane: "一条直行车道",
    congestion_level: "缓慢",
    disposal_measure: "公交车站临时向前迁移约80米",
    event_status: "处理中",
  },
  {
    id: "G018",
    source_type: "群众投诉",
    difficulty: "中等",
    source_text: "群众反映，龙吟路小学门前放学时段临时限行，但指示牌不清晰，接送车辆在支路口反复掉头。",
    event_type: "交通管制",
    event_subtype: "限行措施",
    event_time_text: "放学时段",
    location: "龙吟路小学门前；支路口",
    road_name: "龙吟路",
    vehicles_involved: ["接送车辆"],
    road_impact: "接送车辆在支路口反复掉头",
    congestion_level: "缓慢",
    disposal_measure: "临时限行",
    event_status: "发生中",
  },
  {
    id: "G019",
    source_type: "道路巡查",
    difficulty: "中等",
    source_text: "巡查人员发现，长宁大道与柏林街交叉口东侧人行信号灯不亮，行人和右转车辆通行冲突明显。",
    event_type: "设施故障",
    event_subtype: "信号灯故障",
    location: "长宁大道与柏林街交叉口东侧",
    road_name: "长宁大道；柏林街",
    vehicles_involved: ["右转车辆"],
    road_impact: "行人和右转车辆通行冲突明显",
    congestion_level: "未知",
    event_status: "发生中",
  },
  {
    id: "G020",
    source_type: "交通新闻",
    difficulty: "中等",
    source_text: "受降雪结冰影响，青峰山连接线部分弯道路面湿滑，货车上坡困难，交管部门已撒布融雪剂。",
    event_type: "恶劣天气影响",
    event_subtype: "降雪结冰",
    location: "青峰山连接线部分弯道",
    road_name: "青峰山连接线",
    vehicles_involved: ["货车"],
    road_impact: "路面湿滑，货车上坡困难",
    congestion_level: "缓慢",
    disposal_measure: "撒布融雪剂",
    event_status: "处理中",
  },
  {
    id: "G021",
    source_type: "群众投诉",
    difficulty: "中等",
    source_text: "市民投诉，环湖东路观景台附近旅游大巴长时间占用应急车道上下客，后方车辆只能并线绕行。",
    event_type: "违法行为",
    event_subtype: "占用应急车道",
    location: "环湖东路观景台附近",
    road_name: "环湖东路",
    vehicles_involved: ["旅游大巴", "车辆"],
    road_impact: "后方车辆只能并线绕行",
    occupied_lane: "应急车道",
    congestion_level: "缓慢",
    event_status: "发生中",
  },
  {
    id: "G022",
    source_type: "事故警情",
    difficulty: "中等",
    source_text: "报警人称，白沙大道高架上桥处一辆网约车与三轮车剐蹭，三轮车货物散落，占用右侧两条车道。",
    event_type: "交通事故",
    event_subtype: "车辆剐蹭",
    location: "白沙大道高架上桥处",
    road_name: "白沙大道高架",
    vehicles_involved: ["网约车", "三轮车"],
    vehicle_count: 2,
    road_impact: "货物散落，占用右侧两条车道",
    occupied_lane: "右侧两条车道",
    congestion_level: "拥堵",
    event_status: "发生中",
  },
  {
    id: "G023",
    source_type: "道路巡查",
    difficulty: "中等",
    source_text: "巡查发现，世纪大道会展中心段散场车流集中，停车场出口车辆排队至主路，影响直行车辆。",
    event_type: "道路拥堵",
    event_subtype: "车辆排队",
    location: "世纪大道会展中心段；停车场出口",
    road_name: "世纪大道",
    vehicles_involved: ["车辆"],
    road_impact: "停车场出口车辆排队至主路，影响直行车辆",
    congestion_level: "拥堵",
    event_status: "发生中",
  },
  {
    id: "G024",
    source_type: "交通新闻",
    difficulty: "中等",
    source_text: "地铁站出入口改造期间，丁香路北侧辅道施工占道，非机动车需借用人行道慢行。",
    event_type: "道路施工",
    event_subtype: "占道施工",
    location: "丁香路北侧辅道；地铁站出入口",
    road_name: "丁香路",
    vehicles_involved: ["非机动车"],
    road_impact: "北侧辅道施工占道，非机动车借用人行道慢行",
    occupied_lane: "北侧辅道",
    congestion_level: "缓慢",
    event_status: "发生中",
  },
  {
    id: "G025",
    source_type: "道路巡查",
    difficulty: "中等",
    source_text: "因高压线迁改，竹园路与新城街之间实行半幅通行，货车禁止进入施工路段。",
    event_type: "交通管制",
    event_subtype: "半幅通行",
    location: "竹园路与新城街之间",
    road_name: "竹园路；新城街",
    vehicles_involved: ["货车"],
    road_impact: "实行半幅通行，货车禁止进入施工路段",
    congestion_level: "缓慢",
    disposal_measure: "货车禁止进入",
    event_status: "发生中",
  },
  {
    id: "G026",
    source_type: "群众投诉",
    difficulty: "中等",
    source_text: "群众反映，康乐路公交港湾前方井盖松动，公交车进站时需急打方向避让。",
    event_type: "设施故障",
    event_subtype: "井盖问题",
    location: "康乐路公交港湾前方",
    road_name: "康乐路",
    vehicles_involved: ["公交车"],
    road_impact: "公交车进站时需急打方向避让",
    congestion_level: "未知",
    event_status: "发生中",
  },
  {
    id: "G027",
    source_type: "事故警情",
    difficulty: "中等",
    source_text: "受冰雹天气影响，机场北路部分车辆临时停靠在桥下避险，主线通行速度明显下降。",
    event_type: "恶劣天气影响",
    event_subtype: "强对流天气影响",
    location: "机场北路桥下；主线",
    road_name: "机场北路",
    vehicles_involved: ["车辆"],
    road_impact: "部分车辆临时停靠避险，主线通行速度下降",
    congestion_level: "缓慢",
    event_status: "发生中",
  },
  {
    id: "G028",
    source_type: "道路巡查",
    difficulty: "中等",
    source_text: "巡查发现，江湾路口一辆摩托车逆行进入机动车道，导致对向小客车急刹避让。",
    event_type: "违法行为",
    event_subtype: "逆行",
    location: "江湾路口机动车道",
    road_name: "江湾路",
    vehicles_involved: ["摩托车", "小客车"],
    vehicle_count: 2,
    road_impact: "对向小客车急刹避让",
    congestion_level: "未知",
    event_status: "发生中",
  },
  {
    id: "G029",
    source_type: "事故警情",
    difficulty: "中等",
    source_text: "110转警，瑞云路隧道内一辆小客车撞上检修带护栏，安全气囊弹出，后方车辆排队约200米。",
    event_type: "交通事故",
    event_subtype: "撞护栏事故",
    location: "瑞云路隧道内检修带护栏",
    road_name: "瑞云路隧道",
    vehicles_involved: ["小客车", "车辆"],
    vehicle_count: 1,
    road_impact: "后方车辆排队约200米",
    congestion_level: "拥堵",
    event_status: "发生中",
  },
  {
    id: "G030",
    source_type: "群众投诉",
    difficulty: "中等",
    source_text: "市民反映，南浦广场地下车库出口排队外溢到迎春路，右转车辆连续受阻。",
    event_type: "道路拥堵",
    event_subtype: "车辆排队",
    location: "南浦广场地下车库出口；迎春路",
    road_name: "迎春路",
    vehicles_involved: ["右转车辆"],
    road_impact: "车库出口排队外溢到迎春路，右转车辆受阻",
    congestion_level: "拥堵",
    event_status: "发生中",
  },
  {
    id: "G031",
    source_type: "交通新闻",
    difficulty: "中等",
    source_text: "长青路桥面伸缩缝维修今天上午启动，双向各保留一条车道，现场已摆放锥桶。",
    event_type: "道路施工",
    event_subtype: "道路维修",
    event_time_text: "今天上午",
    location: "长青路桥面",
    road_name: "长青路",
    road_impact: "双向各保留一条车道",
    occupied_lane: "桥面部分车道",
    congestion_level: "缓慢",
    disposal_measure: "现场摆放锥桶",
    event_status: "发生中",
  },
  {
    id: "G032",
    source_type: "道路巡查",
    difficulty: "中等",
    source_text: "巡查记录，科创三路园区门前因大型设备进场实施临时管控，社会车辆需从雅竹街绕行。",
    event_type: "交通管制",
    event_subtype: "临时管制",
    location: "科创三路园区门前；雅竹街",
    road_name: "科创三路；雅竹街",
    vehicles_involved: ["社会车辆"],
    road_impact: "社会车辆需从雅竹街绕行",
    congestion_level: "未知",
    disposal_measure: "绕行雅竹街",
    event_status: "发生中",
  },
  {
    id: "G033",
    source_type: "交通新闻",
    difficulty: "中等",
    source_text: "交管部门通报，滨湖隧道入口可变车道指示屏故障，入口车辆按地面标线通行。",
    event_type: "设施故障",
    event_subtype: "指示屏故障",
    location: "滨湖隧道入口",
    road_name: "滨湖隧道",
    vehicles_involved: ["车辆"],
    road_impact: "入口车辆按地面标线通行",
    congestion_level: "未知",
    disposal_measure: "按地面标线通行",
    event_status: "处理中",
  },
  {
    id: "G034",
    source_type: "群众投诉",
    difficulty: "中等",
    source_text: "居民反映，连续降雨后银沙路低洼点积水漫过路缘，电动车只能推行通过。",
    event_type: "恶劣天气影响",
    event_subtype: "道路积水",
    event_time_text: "连续降雨后",
    location: "银沙路低洼点",
    road_name: "银沙路",
    vehicles_involved: ["电动车"],
    road_impact: "积水漫过路缘，电动车只能推行通过",
    congestion_level: "缓慢",
    event_status: "发生中",
  },
  {
    id: "G035",
    source_type: "交通新闻",
    difficulty: "中等",
    source_text: "交警夜查发现，开元路一名驾驶人涉嫌酒驾，车辆停在检查区外侧车道接受处理。",
    event_type: "违法行为",
    event_subtype: "酒驾",
    location: "开元路检查区外侧车道",
    road_name: "开元路",
    vehicles_involved: ["车辆"],
    vehicle_count: 1,
    road_impact: "车辆停在检查区外侧车道接受处理",
    occupied_lane: "外侧车道",
    congestion_level: "未知",
    disposal_measure: "接受处理",
    event_status: "处理中",
  },
  {
    id: "G036",
    source_type: "事故警情",
    difficulty: "复杂",
    source_text: "报警人称，7时40分左右，芙蓉高架由西向东在月华匝道至中央公园出口之间，一辆厢式货车追尾小客车后又与右侧公交车剐蹭，占用中间和右侧两条车道，1人轻伤，队尾已排至月华匝道。",
    event_type: "交通事故",
    event_subtype: "多车事故",
    event_time_text: "7时40分左右",
    location: "芙蓉高架由西向东月华匝道至中央公园出口之间",
    road_name: "芙蓉高架；月华匝道；中央公园出口",
    vehicles_involved: ["厢式货车", "小客车", "公交车"],
    vehicle_count: 3,
    casualties: "1人轻伤",
    injured_count: 1,
    death_count: 0,
    road_impact: "占用中间和右侧两条车道，队尾排至月华匝道",
    occupied_lane: "中间和右侧两条车道",
    congestion_level: "严重拥堵",
    event_status: "发生中",
  },
  {
    id: "G037",
    source_type: "道路巡查",
    difficulty: "复杂",
    source_text: "巡查发现，金石大道进城方向从莲花立交到体育馆西门车流持续积压，辅路停车场出口、主路掉头口和公交站同时排队，公交车、小客车、网约车相互穿插，通行效率明显下降。",
    event_type: "道路拥堵",
    event_subtype: "严重拥堵",
    location: "金石大道进城方向莲花立交至体育馆西门；辅路停车场出口；主路掉头口；公交站",
    road_name: "金石大道；莲花立交",
    vehicles_involved: ["公交车", "小客车", "网约车"],
    road_impact: "多点排队，车辆相互穿插，通行效率明显下降",
    congestion_level: "严重拥堵",
    event_status: "发生中",
  },
  {
    id: "G038",
    source_type: "交通新闻",
    difficulty: "复杂",
    source_text: "因排水箱涵夜间施工，鹭岛路与平安街交叉口至滨江南路段将分两阶段占道，第一阶段封闭南向北两条直行车道，第二阶段调整公交站点，过往公交车和社会车辆需按诱导屏绕行。",
    event_type: "道路施工",
    event_subtype: "分阶段占道施工",
    event_time_text: "夜间",
    location: "鹭岛路与平安街交叉口至滨江南路段",
    road_name: "鹭岛路；平安街；滨江南路",
    vehicles_involved: ["公交车", "社会车辆"],
    road_impact: "分两阶段占道，封闭南向北两条直行车道并调整公交站点",
    occupied_lane: "南向北两条直行车道",
    congestion_level: "缓慢",
    disposal_measure: "按诱导屏绕行",
    event_status: "发生中",
  },
  {
    id: "G039",
    source_type: "交通新闻",
    difficulty: "复杂",
    source_text: "大型演唱会散场期间，奥体东路、星光南街和会展支路将实行分时段交通管制，出租车和网约车只能在P3停车场落客，公交接驳车优先通行，周边社会车辆需绕行春晖大道。",
    event_type: "交通管制",
    event_subtype: "活动交通管制",
    event_time_text: "大型演唱会散场期间",
    location: "奥体东路；星光南街；会展支路；P3停车场；春晖大道",
    road_name: "奥体东路；星光南街；会展支路；春晖大道",
    vehicles_involved: ["出租车", "网约车", "公交接驳车", "社会车辆"],
    road_impact: "分时段管制，部分车辆限制落客，周边车辆绕行",
    congestion_level: "未知",
    disposal_measure: "公交接驳车优先通行，社会车辆绕行春晖大道",
    event_status: "发生中",
  },
  {
    id: "G040",
    source_type: "道路巡查",
    difficulty: "复杂",
    source_text: "巡查至松江立交时发现，西侧匝道信号灯灭灯，同时桥下导向标志牌被风吹倒，进入主路的货车和小客车多次急停，后方出现短时排队。",
    event_type: "设施故障",
    event_subtype: "多设施故障",
    location: "松江立交西侧匝道；桥下",
    road_name: "松江立交",
    vehicles_involved: ["货车", "小客车"],
    road_impact: "车辆多次急停，后方短时排队",
    congestion_level: "缓慢",
    event_status: "发生中",
  },
  {
    id: "G041",
    source_type: "交通新闻",
    difficulty: "复杂",
    source_text: "受强降雨和大风叠加影响，外港高速临海收费站至北港互通路段多处积水，部分标志牌倾斜，危化品车、旅游客车和小客车均被要求降速通行，交警在收费站外实施分流。",
    event_type: "恶劣天气影响",
    event_subtype: "暴雨大风影响",
    location: "外港高速临海收费站至北港互通路段；收费站外",
    road_name: "外港高速；临海收费站；北港互通",
    vehicles_involved: ["危化品车", "旅游客车", "小客车"],
    road_impact: "多处积水，部分标志牌倾斜，车辆降速通行",
    congestion_level: "拥堵",
    disposal_measure: "收费站外实施分流",
    event_status: "处理中",
  },
  {
    id: "G042",
    source_type: "群众投诉",
    difficulty: "复杂",
    source_text: "多名市民反映，华庭路美食街周边晚间存在外卖电动车逆行、网约车占用公交站上下客、私家车违停三类问题，公交车无法正常靠站，非机动车被迫进入机动车道。",
    event_type: "违法行为",
    event_subtype: "多类违法行为",
    event_time_text: "晚间",
    location: "华庭路美食街周边；公交站；机动车道",
    road_name: "华庭路",
    vehicles_involved: ["外卖电动车", "网约车", "私家车", "公交车", "非机动车"],
    road_impact: "公交车无法正常靠站，非机动车被迫进入机动车道",
    occupied_lane: "公交站；机动车道",
    congestion_level: "缓慢",
    event_status: "发生中",
  },
  {
    id: "G043",
    source_type: "事故警情",
    difficulty: "复杂",
    source_text: "接警称，晚间莲池大道东向西接近凤鸣路口处，一辆渣土车避让电动车时碰撞中央隔离墩，后方两辆小轿车连续追尾，现场散落物占用左侧车道和部分掉头车道，2人受伤。",
    event_type: "交通事故",
    event_subtype: "多车连续事故",
    event_time_text: "晚间",
    location: "莲池大道东向西接近凤鸣路口处",
    road_name: "莲池大道；凤鸣路",
    vehicles_involved: ["渣土车", "电动车", "小轿车"],
    vehicle_count: 4,
    casualties: "2人受伤",
    injured_count: 2,
    death_count: 0,
    road_impact: "散落物占用左侧车道和部分掉头车道",
    occupied_lane: "左侧车道；部分掉头车道",
    congestion_level: "拥堵",
    event_status: "发生中",
  },
  {
    id: "G044",
    source_type: "道路巡查",
    difficulty: "复杂",
    source_text: "巡查记录显示，东河隧道南口、北口和相邻辅路同时出现排队，原因是隧道内前方车流饱和，货车低速爬坡，小客车频繁变道，排队影响到滨河二路入口。",
    event_type: "道路拥堵",
    event_subtype: "多点排队拥堵",
    location: "东河隧道南口；北口；相邻辅路；滨河二路入口",
    road_name: "东河隧道；滨河二路",
    vehicles_involved: ["货车", "小客车"],
    road_impact: "隧道两端和辅路排队，影响滨河二路入口",
    congestion_level: "严重拥堵",
    event_status: "发生中",
  },
  {
    id: "G045",
    source_type: "群众投诉",
    difficulty: "复杂",
    source_text: "群众投诉称，梅园路排污管施工围挡从路口延伸到小区出口，早高峰只剩一条车道，小区车辆、公交车和送货货车交织通行，学校门前接送区也被压缩。",
    event_type: "道路施工",
    event_subtype: "施工围挡影响通行",
    event_time_text: "早高峰",
    location: "梅园路路口至小区出口；学校门前接送区",
    road_name: "梅园路",
    vehicles_involved: ["小区车辆", "公交车", "送货货车"],
    road_impact: "只剩一条车道，车辆交织通行，学校门前接送区被压缩",
    occupied_lane: "多条机动车道",
    congestion_level: "拥堵",
    event_status: "发生中",
  },
  {
    id: "G046",
    source_type: "交通新闻",
    difficulty: "复杂",
    source_text: "因跨江烟花活动安保需要，江月桥主桥、滨水路观景平台入口和江南大道下穿匝道将同步管制，公交线路临时改道，网约车不得在桥头停靠，行人通道分批放行。",
    event_type: "交通管制",
    event_subtype: "活动交通管制",
    location: "江月桥主桥；滨水路观景平台入口；江南大道下穿匝道",
    road_name: "江月桥；滨水路；江南大道",
    vehicles_involved: ["公交车", "网约车", "行人"],
    road_impact: "多处同步管制，公交改道，网约车不得桥头停靠，行人分批放行",
    congestion_level: "未知",
    disposal_measure: "公交线路临时改道，行人通道分批放行",
    event_status: "发生中",
  },
  {
    id: "G047",
    source_type: "道路巡查",
    difficulty: "复杂",
    source_text: "巡查发现，机场南线彩虹桥下方连续三块限高提示牌缺失，旁边路灯不亮，夜间大型客车和厢式货车进入前反复减速确认，后方小客车排队避让。",
    event_type: "设施故障",
    event_subtype: "标志牌缺失",
    event_time_text: "夜间",
    location: "机场南线彩虹桥下方",
    road_name: "机场南线；彩虹桥",
    vehicles_involved: ["大型客车", "厢式货车", "小客车"],
    road_impact: "车辆反复减速确认，后方小客车排队避让",
    congestion_level: "缓慢",
    event_status: "发生中",
  },
  {
    id: "G048",
    source_type: "事故警情",
    difficulty: "复杂",
    source_text: "接群众报警，台风外围降雨导致海港大道涵洞积水加深，已有一辆小轿车涉水熄火，一辆公交车停在入口外等待，后方货车和网约车排队，交警已封控涵洞两端。",
    event_type: "恶劣天气影响",
    event_subtype: "台风降雨积水",
    location: "海港大道涵洞；涵洞两端",
    road_name: "海港大道",
    vehicles_involved: ["小轿车", "公交车", "货车", "网约车"],
    vehicle_count: 4,
    road_impact: "小轿车涉水熄火，公交车等待，后方车辆排队",
    congestion_level: "拥堵",
    disposal_measure: "交警封控涵洞两端",
    event_status: "处理中",
  },
  {
    id: "G049",
    source_type: "交通新闻",
    difficulty: "复杂",
    source_text: "交警通报，晨风大道快速入口查处多起违法行为：一辆货车超速进入匝道，一辆轿车实线变道，一辆电动车闯入机动车入口，现场短时占用检查区和右侧车道。",
    event_type: "违法行为",
    event_subtype: "多类违法行为",
    location: "晨风大道快速入口；匝道；检查区",
    road_name: "晨风大道",
    vehicles_involved: ["货车", "轿车", "电动车"],
    vehicle_count: 3,
    road_impact: "短时占用检查区和右侧车道",
    occupied_lane: "检查区；右侧车道",
    congestion_level: "缓慢",
    disposal_measure: "交警现场查处",
    event_status: "处理中",
  },
  {
    id: "G050",
    source_type: "事故警情",
    difficulty: "复杂",
    source_text: "报警显示，花城大道南向北在人民医院急诊入口、公交港湾和掉头区附近，一辆救护车与私家车轻微碰撞后停在路中，旁边一辆电动自行车倒地，急诊入口车辆进出受阻，现场需要交警和医院保安共同疏导。",
    event_type: "交通事故",
    event_subtype: "车辆碰撞",
    location: "花城大道南向北人民医院急诊入口；公交港湾；掉头区",
    road_name: "花城大道",
    vehicles_involved: ["救护车", "私家车", "电动自行车"],
    vehicle_count: 3,
    road_impact: "急诊入口车辆进出受阻",
    congestion_level: "拥堵",
    disposal_measure: "交警和医院保安共同疏导",
    event_status: "发生中",
  },
];

const existingPhrases = [
  "建设路与民安街",
  "东环高架",
  "长江路西段",
  "人民大道隧道",
  "解放路小学",
  "机场快速路",
  "新华桥",
  "北二环辅路",
  "滨河路",
  "南山路",
  "和平街",
  "环城高速K45",
  "西湖路",
  "开发区大道",
  "站前路",
  "迎宾大道",
  "幸福路菜市场",
  "金桂街",
  "龙泉路",
  "兴业路铁路涵洞",
  "万达广场",
  "东风路",
  "河西大街",
  "中山路",
  "外环东路",
  "友谊路",
  "南湖大桥",
  "体育中心",
  "人民路与广场街",
];

if (records.length !== 50) throw new Error(`Expected 50 records, got ${records.length}`);

const eventCounts = new Map();
const difficultyCounts = new Map();
const sourceCounts = new Map();
for (const record of records) {
  eventCounts.set(record.event_type, (eventCounts.get(record.event_type) ?? 0) + 1);
  difficultyCounts.set(record.difficulty, (difficultyCounts.get(record.difficulty) ?? 0) + 1);
  sourceCounts.set(record.source_type, (sourceCounts.get(record.source_type) ?? 0) + 1);
  if (!codes[record.event_type]) throw new Error(`Missing code for ${record.id}`);
  if (existingPhrases.some((phrase) => record.source_text.includes(phrase))) {
    throw new Error(`Record ${record.id} appears to reuse an existing sample phrase`);
  }
}

const expectedDifficulty = new Map([["简单", 15], ["中等", 20], ["复杂", 15]]);
for (const [difficulty, count] of expectedDifficulty) {
  if (difficultyCounts.get(difficulty) !== count) {
    throw new Error(`Difficulty ${difficulty} expected ${count}, got ${difficultyCounts.get(difficulty)}`);
  }
}

const rows = records.map((record) => {
  const std = standard(record);
  return [
    record.id,
    record.source_type,
    record.source_text,
    record.event_type,
    record.event_subtype,
    JSON.stringify(std),
  ];
});

const workbook = Workbook.create();
const sheet = workbook.worksheets.add("Generalization_Test");
sheet.showGridLines = false;
sheet.getRange("A1:F51").values = [[
  "id",
  "source_type",
  "source_text",
  "event_type",
  "event_subtype",
  "Standard_JSON",
], ...rows];

const used = sheet.getRange("A1:F51");
used.format.font = { name: "Microsoft YaHei", size: 10 };
used.format.wrapText = true;
used.format.borders = { preset: "all", style: "thin", color: "#C9D6E2" };
sheet.getRange("A1:F1").format = {
  fill: "#1F4E78",
  font: { name: "Microsoft YaHei", size: 10, bold: true, color: "#FFFFFF" },
  wrapText: true,
};
sheet.getRange("A:A").format.columnWidth = 9;
sheet.getRange("B:B").format.columnWidth = 14;
sheet.getRange("C:C").format.columnWidth = 80;
sheet.getRange("D:D").format.columnWidth = 16;
sheet.getRange("E:E").format.columnWidth = 24;
sheet.getRange("F:F").format.columnWidth = 120;
sheet.getRange("A1:F1").format.rowHeight = 24;
sheet.getRange("A2:F51").format.rowHeight = 78;
sheet.freezePanes.freezeRows(1);
sheet.tables.add("A1:F51", true, "GeneralizationTestTable");

const summary = workbook.worksheets.add("Summary");
summary.showGridLines = false;
summary.getRange("A1:F1").merge();
summary.getRange("A1").values = [["交通事件泛化测试数据集汇总"]];
summary.getRange("A1").format = {
  fill: "#1F4E78",
  font: { name: "Microsoft YaHei", size: 16, bold: true, color: "#FFFFFF" },
  horizontalAlignment: "center",
};
summary.getRange("A3:B6").values = [
  ["指标", "数量"],
  ["样本总数", records.length],
  ["事件类型数", eventCounts.size],
  ["来源类型数", sourceCounts.size],
];
summary.getRange("D3:E10").values = [["event_type", "count"], ...[...eventCounts.entries()]];
summary.getRange("A9:B12").values = [["difficulty", "count"], ...[...difficultyCounts.entries()]];
summary.getRange("D13:E17").values = [["source_type", "count"], ...[...sourceCounts.entries()]];
for (const range of ["A3:B6", "D3:E10", "A9:B12", "D13:E17"]) {
  const r = summary.getRange(range);
  r.format.font = { name: "Microsoft YaHei", size: 10 };
  r.format.borders = { preset: "all", style: "thin", color: "#C9D6E2" };
  r.format.wrapText = true;
}
for (const range of ["A3:B3", "D3:E3", "A9:B9", "D13:E13"]) {
  summary.getRange(range).format = {
    fill: "#D9EAF7",
    font: { name: "Microsoft YaHei", size: 10, bold: true, color: "#17365D" },
  };
}
summary.getRange("A:E").format.columnWidth = 18;

const sampleCheck = await workbook.inspect({
  kind: "table",
  range: "Generalization_Test!A1:F6",
  include: "values",
  tableMaxRows: 6,
  tableMaxCols: 6,
});
console.log(sampleCheck.ndjson);

const errorScan = await workbook.inspect({
  kind: "match",
  searchTerm: "#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",
  options: { useRegex: true, maxResults: 300 },
  summary: "final formula error scan",
});
console.log(errorScan.ndjson);

for (const sheetName of ["Generalization_Test", "Summary"]) {
  const preview = await workbook.render({ sheetName, autoCrop: "all", scale: 1, format: "png" });
  await fs.writeFile(`${outputDir}/${sheetName}.png`, new Uint8Array(await preview.arrayBuffer()));
}

const xlsx = await SpreadsheetFile.exportXlsx(workbook);
await xlsx.save(`${outputDir}/traffic_generalization_test_50.xlsx`);

await fs.writeFile(
  `${outputDir}/quality_report.json`,
  JSON.stringify({
    total: records.length,
    eventCounts: Object.fromEntries(eventCounts),
    difficultyCounts: Object.fromEntries(difficultyCounts),
    sourceCounts: Object.fromEntries(sourceCounts),
    standardJsonFields: fields,
  }, null, 2),
  "utf8",
);
